name: Generate Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics
          token: ${{ secrets.METRICS_TOKEN }}
          user: KozmikLojik
          template: classic
          config_timezone: Asia/Calcutta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_stargazers: yes
          plugin_stargazers_worldmap: yes
          plugin_commit_time: yes
          plugin_lines: yes
          plugin_activity: yes
          commits_author: KozmikLojik
          output_action: commit
          committer_name: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
